# Generated by Django 3.0.2 on 2020-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='no_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='semestre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
